AllData<-read.table("./household_power_consumption.txt",stringsAsFactors = FALSE, header = TRUE, sep = ";")
DT<-strptime(paste(AllData$Date, AllData$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
AllData<-cbind(AllData, DT)
AllData$Date<-as.Date(AllData$Date, format="%d/%m/%Y")
AllData$Time<-format(AllData$Time, format = "%H:%M:%S")
AllData$Global_active_power<-as.numeric(AllData$Global_active_power)
Global_active_power<-as.numeric(data1$Global_active_power)
data1<-subset(AllData, Date == "2007-02-01" | Date =="2007-02-02")
data1$Sub_metering_1<-as.numeric(data1$Sub_metering_1)
data1$Sub_metering_2<-as.numeric(data1$Sub_metering_2)
data1$Sub_metering_3<-as.numeric(data1$Sub_metering_3)

png("plot3.png")
with(data1, plot(DT, Sub_metering_1,type = "l", xlab = "Day", ylab = "Energy Sub Metering"))
lines(data1$DT, data1$Sub_metering_2, col = "red")
lines(data1$DT, data1$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"),lty = 1)
dev.off()
  
