AllData<-read.table("./household_power_consumption.txt",stringsAsFactors = FALSE, header = TRUE, sep = ";")
DT<-strptime(paste(AllData$Date, AllData$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
AllData<-cbind(AllData, DT)
AllData$Date<-as.Date(AllData$Date, format="%d/%m/%Y")
AllData$Time<-format(AllData$Time, format = "%H:%M:%S")
AllData$Global_active_power<-as.numeric(AllData$Global_active_power)
AllData$Global_active_power<-as.numeric(AllData$Global_active_power)
AllData$Voltage<-as.numeric(AllData$Voltage)
AllData$Global_reactive_power<-as.numeric(AllData$Global_reactive_power)
data1<-subset(AllData, Date == "2007-02-01" | Date =="2007-02-02")

png("plot4.png")
par(mfrow = c(2,2), mar = c(4,4, 0.5,0.5))
with(data1, plot(DT, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power"))
with(data1, plot(DT, Voltage, type = "l", xlab = "datetime", lwd = 0.05))
with(data1, plot(DT, Sub_metering_1,type = "l", xlab = "", ylab = "Energy Sub Metering"))
lines(data1$DT, data1$Sub_metering_2, col = "red")
lines(data1$DT, data1$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"),lty = 1, bty = "n")
with(data1, plot(DT, Global_reactive_power, type = "l", xlab = "datetime", lwd = 0.05))
dev.off()
